### ISSUE TITLE
installing cmake on macOS

### ISSUE THREAD

**Issue by Justiniscoding** [Justiniscoding/Brute-Force-In-Many-Different-Languages#6]
i need to install LOLCODE on my imac running MacOS El Capitan. one of the commands is cmake . how do i install cmake?

**Comment by RedYetiDev** [comment]
If you have `homebrew/brew`:
`brew install cmake`

If not:
[cmake-3.20.0-rc1.tar.gz](https://github.com/Kitware/CMake/releases/download/v3.20.0-rc1/cmake-3.20.0-rc1.tar.gz)

**Comment by RedYetiDev** [comment]
Please go into the repo settings and enable GitHub Pages for the `gh-pages` branch.

**Comment by Justiniscoding** [comment]
I installed cmake, now lolcode is not working. and why the gh-pages branch?

**Comment by Justiniscoding** [comment]
i did it

**Comment by Justiniscoding** [comment]
@RedYetiDev  where will the website be?

**Comment by RedYetiDev** [comment]
1. Your welcome on the website.
2. Have you installed [LCI](https://github.com/justinmeza/lci)?

**Comment by Justiniscoding** [comment]
i tried. i cloned the repo, run cmake ., make but i got an error when i did make install

**Comment by RedYetiDev** [comment]
What is the error

**Comment by Justiniscoding** [comment]
i can’t remember, i will tell you later, right now i will work on the LOLCode brute force

**Comment by RedYetiDev** [comment]
ok

**Comment by Justiniscoding** [comment]
do you know LOL code?

**Comment by Justiniscoding** [comment]
the loops are really weird

**Comment by Justiniscoding** [comment]
after a do LOLCode i will work on java

**Comment by RedYetiDev** [comment]
Actually, I don't know LOL CODE very well, but the installation seems to be similar other code.

**Comment by Justiniscoding** [comment]
@RedYetiDev  done java!

**Comment by Justiniscoding** [comment]
@RedYetiDev on LOLCODE it does not say how to download it. update the website please

**Comment by RedYetiDev** [comment]
OK, will do.

**Comment by Justiniscoding** [comment]
@RedYetiDev add java to the list

**Comment by Justiniscoding** [comment]
and i will give you the LOL code installation error

**Comment by Justiniscoding** [comment]
nevermind about lolcode, the download worked

**Comment by RedYetiDev** [comment]
Good
