### ISSUE TITLE
where is the list of supported languages?

### ISSUE THREAD

**Issue by Justiniscoding** [Justiniscoding/Brute-Force-In-Many-Different-Languages#7]
@RedYetiDev you made the site. where are the supported languages. i need to change them. i need to add java

**Comment by RedYetiDev** [comment]
see `Creating Posts` in the [DarkFolio Documentation](https://redyetidev.github.io/DarkFolio/DarkFolio/)

**Comment by RedYetiDev** [comment]
Set the image to `https://upload.wikimedia.org/wikipedia/en/3/30/Java_programming_language_logo.svg`
Do you just want me to do it?

**Comment by Justiniscoding** [comment]
i did the image but at the very starting of it it says

**Comment by Justiniscoding** [comment]
> i did the image but at the very starting of it it says

Currently, the supported languages are LOLCODE, C++, Javascript, and Python

**Comment by RedYetiDev** [comment]
I will fix that part.

**Comment by Justiniscoding** [comment]
where can i edit that to add java?
